services:
  - type: web
    name: localbite-backend
    env: python
    plan: free
    rootDir: backend/api-gateway
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
